name: run-tests
on: [push]
jobs:
 run-tests:
  runs-on: ubuntu-20.04
  steps:
   - uses: actions/checkout@v2
   - name: start server
     run: |
      sudo pip install django
      cd GiftcardSite
      sudo nohup python3 manage.py runserver 80 > server.out &
   - name: test for xss vulnerability
     run: python3 ./hr2340-xss.py
   - name: test for csrf vulnerability
     run: python3 ./hr2340-csrf.py
   - name: test for sqli vulnerability
     run: python3 ./hr2340-sqli.py
   - name: test for cmdi vulnerability
     run: python3 ./hr2340-cmdi.py
